postgres:       &postgres
  adapter:      postgresql
  encoding:     unicode
  host:         localhost
  min_messages: warning
  username:     netengine
  password:     <%= ENV['PASSWORD'] %>

development:
  <<: *postgres
  database:     rhok_brisbane_2014_dev

test:
  <<: *postgres
  database:     rhok_brisbane_2014_test

production:
  <<: *postgres
  database:     rhok_brisbane_2014_production
